name: Nix

on:
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: cachix/install-nix-action@v31

      - name: Check flake
        run: nix flake check --print-build-logs
